### PR TITLE
Allow tests to work down to Firefox v2

### PR DESCRIPTION
**Pull request by david-dick**
This is some fixes required to test down to Firefox v2.  Getting v1 to work requires redoing all the map code at least.

### CODE REVIEW

**Comment by lraj22** [comment]
Have you tested this? I'm thinking of removing support for Firefox 1-5 due to low usage. The first Firefox version currently explicitly tested is 11 so far, anyways. I'll approve this PR with some changes when I have a bit more time to review and test it.

**Comment by david-dick** [comment]
I'm happy with just removing support for Firefox 1-5.   I've only tested it in a mock environment.

**Review by lraj22 — APPROVED** [review]
Thanks for improving backwards compatibility, also included in this update is now a minimum FF version of 6.

**Comment by lraj22** [comment]
Once again, thanks @david-dick, your help is much appreciated. Merged 👍

**Pull request merged**
