### PR TITLE
Removing alerts

### PR DESCRIPTION
**Pull request by david-dick**
It would be nice to be able to display errors when popups are disabled.  What tool are you using to minify your javascript?  It would be good to see some documentation for that.

### CODE REVIEW

**Comment by lraj22** [comment]
Your pull request seems good. I am busy currently and still need to do a bit of review, but this will hopefully be merged soon. Thank you for noticing this!

**Comment by lraj22** [comment]
@david-dick I've made one change, which is to use `var` instead of `let`. The intent is to work on as many browser versions as possible. Regarding the minifier tool, I used https://www.toptal.com/developers/javascript-minifier . Nothing special about that specific tool, it's just the first one that showed up.
Let me know if this is good to commit. Thanks!

**Comment by david-dick** [comment]
works for me!

**Comment by lraj22** [comment]
Hey @david-dick, I appreciate the PR a lot, you're the first person to ever write any PR or issue on any of my repos... thank you!! As for the PR itself, it's been merged. 👍

**Pull request merged**
